### ISSUE TITLE
unable to catch other http Errors than 500

### ISSUE THREAD

**Issue by coeur85** [salihcantekin/TechBuddySolution#5]
I'm having an issue trigging the Exception Handling Middleware.
my app is generating 401 un authorized.
and 404  not found.

I'm trying to override those errors with custom model and return the result in a different response code than the one was originally generated.

for example i return the 404 as Bad Request status code  400
and in my custom model i've a error message property that holds a friendly message to the user

**Comment by salihcantekin** [comment]
They are actually not an exact example of Exceptions. This middleware is built to catch only unhandled exceptions. So when the httpstatuscode is 404 or 401, there should be a mechanism in your project that throws an exception or there can be another middleware for this purpose I can develop.
